import { ShieldCheck, Users, Compass, Globe, Mountain, Waves, TreePine, MapPin } from "lucide-react";

export const HERO_IMAGES = [
  "https://images.pexels.com/photos/31340332/pexels-photo-31340332.jpeg?auto=compress&cs=tinysrgb&w=1920",
  "https://images.pexels.com/photos/573850/pexels-photo-573850.jpeg?auto=compress&cs=tinysrgb&w=1920",
  "https://images.pexels.com/photos/1006360/pexels-photo-1006360.jpeg?auto=compress&cs=tinysrgb&w=1920",
  "https://images.pexels.com/photos/16141092/pexels-photo-16141092.jpeg?auto=compress&cs=tinysrgb&w=1920",
  "https://images.pexels.com/photos/4982560/pexels-photo-4982560.jpeg?auto=compress&cs=tinysrgb&w=1920",
  "https://images.pexels.com/photos/31533424/pexels-photo-31533424.jpeg?auto=compress&cs=tinysrgb&w=1920",
];

export const destinations = [
  {
    id: "philippines",
    title: "The Philippines",
    subtitle: "7,641 Islands of Wonder",
    tagline: "Crystal waters, limestone cliffs & the world's best beaches",
    image: "https://images.pexels.com/photos/31340332/pexels-photo-31340332.jpeg?auto=compress&cs=tinysrgb&w=1280",
    price: "From £350",
    rating: 4.9,
    reviews: 15420,
    icon: Globe,
    tag: "islands",
    region: "Southeast Asia",
    vibe: "Diverse & Vast",
  },
  {
    id: "siargao",
    title: "Siargao Island",
    tagline: "The Social Heartbeat",
    image: "https://images.pexels.com/photos/3533659/pexels-photo-3533659.jpeg?auto=compress&cs=tinysrgb&w=800",
    rating: 4.9,
    region: "Mindanao",
    vibe: "Electric & Communal",
    tag: "islands",
    price: "From £280",
    reviews: 765,
    icon: Waves,
  },
  {
    id: "el-nido",
    title: "El Nido, Palawan",
    tagline: "The Archipelago King",
    image: "https://images.pexels.com/photos/31340332/pexels-photo-31340332.jpeg?auto=compress&cs=tinysrgb&w=800",
    rating: 4.8,
    region: "Palawan",
    vibe: "Majestic & Explorative",
    tag: "islands",
    price: "From £499",
    reviews: 1240,
    icon: Waves,
  },
  {
    id: "coron",
    title: "Coron, Palawan",
    tagline: "The Deep Sea Frontier",
    image: "https://images.pexels.com/photos/13518466/pexels-photo-13518466.jpeg?auto=compress&cs=tinysrgb&w=800",
    rating: 4.7,
    region: "Palawan",
    vibe: "Raw & Adventurous",
    tag: "islands",
    price: "From £450",
    reviews: 865,
    icon: Waves,
  },
  {
    id: "cebu",
    title: "Cebu & Moalboal",
    tagline: "The Adventure Nexus",
    image: "https://images.pexels.com/photos/17263722/pexels-photo-17263722.jpeg?auto=compress&cs=tinysrgb&w=800",
    rating: 4.8,
    region: "Visayas",
    vibe: "Vibrant & Thrilling",
    tag: "islands",
    price: "From £380",
    reviews: 1540,
    icon: Waves,
  },
  {
    id: "siquijor",
    title: "Siquijor Island",
    tagline: "The Mystic Sanctuary",
    image: "https://images.pexels.com/photos/14634010/pexels-photo-14634010.jpeg?auto=compress&cs=tinysrgb&w=800",
    rating: 4.9,
    region: "Visayas",
    vibe: "Ethereal & Tranquil",
    tag: "islands",
    price: "From £220",
    reviews: 430,
    icon: Waves,
  },
  {
    id: "boracay",
    title: "Boracay Island",
    tagline: "The Ivory Playground",
    image: "https://images.pexels.com/photos/33676228/pexels-photo-33676228.jpeg?auto=compress&cs=tinysrgb&w=800",
    rating: 4.6,
    region: "Visayas",
    vibe: "Vibrant & Pristine",
    tag: "islands",
    price: "From £320",
    reviews: 980,
    icon: Waves,
  },
  {
    id: "batanes",
    title: "Batanes Islands",
    tagline: "The Northern Soul",
    image: "https://images.pexels.com/photos/20788066/pexels-photo-20788066.jpeg?auto=compress&cs=tinysrgb&w=800",
    rating: 5.0,
    region: "Northern Luzon",
    vibe: "Majestic & Tranquil",
    tag: "mountains",
    price: "From £450",
    reviews: 320,
    icon: Mountain,
  },
  {
    id: "camiguin",
    title: "Camiguin Island",
    tagline: "The Island Born of Fire",
    image: "https://images.pexels.com/photos/29152393/pexels-photo-29152393.jpeg?auto=compress&cs=tinysrgb&w=800",
    rating: 4.7,
    region: "Mindanao",
    vibe: "Ethereal & Volcanic",
    tag: "islands",
    price: "From £260",
    reviews: 215,
    icon: Waves,
  },
  {
    id: "bohol",
    title: "Bohol",
    tagline: "Chocolate Hills & Tarsiers",
    image: "https://images.pexels.com/photos/16141092/pexels-photo-16141092.jpeg?auto=compress&cs=tinysrgb&w=800",
    rating: 4.8,
    region: "Visayas",
    vibe: "Natural & Curious",
    tag: "islands",
    price: "From £310",
    reviews: 890,
    icon: Waves,
  },
  {
    id: "sagada",
    title: "Sagada",
    tagline: "Clouds & Hanging Coffins",
    image: "https://images.pexels.com/photos/4982560/pexels-photo-4982560.jpeg?auto=compress&cs=tinysrgb&w=800",
    rating: 4.9,
    region: "Mountain Province",
    vibe: "Mystical & Chilly",
    tag: "mountains",
    price: "From £290",
    reviews: 560,
    icon: Mountain,
  },
  {
    id: "vigan",
    title: "Vigan City",
    tagline: "Spanish Colonial Heritage",
    image: "https://images.pexels.com/photos/1006360/pexels-photo-1006360.jpeg?auto=compress&cs=tinysrgb&w=800",
    rating: 4.7,
    region: "Ilocos Sur",
    vibe: "Historic & Timeless",
    tag: "cities",
    price: "From £240",
    reviews: 1200,
    icon: MapPin,
  },
  {
    id: "puerto-princesa",
    title: "Puerto Princesa",
    tagline: "Subterranean River Wonders",
    image: "https://images.pexels.com/photos/31533424/pexels-photo-31533424.jpeg?auto=compress&cs=tinysrgb&w=800",
    rating: 4.8,
    region: "Palawan",
    vibe: "Wild & Lush",
    tag: "jungles",
    price: "From £360",
    reviews: 1100,
    icon: TreePine,
  },
  {
    id: "manila",
    title: "Metro Manila",
    tagline: "The Pulse of the Pearl",
    image: "https://images.pexels.com/photos/573850/pexels-photo-573850.jpeg?auto=compress&cs=tinysrgb&w=800",
    rating: 4.5,
    region: "Luzon",
    vibe: "Dynamic & Urban",
    tag: "cities",
    price: "From £180",
    reviews: 25000,
    icon: MapPin,
  },
  {
    id: "davao",
    title: "Davao City",
    tagline: "The Durian Capital",
    image: "https://images.pexels.com/photos/16141092/pexels-photo-16141092.jpeg?auto=compress&cs=tinysrgb&w=800",
    rating: 4.7,
    region: "Mindanao",
    vibe: "Orderly & Tropical",
    tag: "cities",
    price: "From £210",
    reviews: 3400,
    icon: MapPin,
  },
  {
    id: "bukidnon",
    title: "Bukidnon",
    tagline: "Pineapples & Highlands",
    image: "https://images.pexels.com/photos/4982560/pexels-photo-4982560.jpeg?auto=compress&cs=tinysrgb&w=800",
    rating: 4.8,
    region: "Northern Mindanao",
    vibe: "Fresh & Scenic",
    tag: "mountains",
    price: "From £270",
    reviews: 420,
    icon: Mountain,
  },
];

export const features = [
  {
    icon: ShieldCheck,
    title: "Verified Companions",
    desc: "Every member is ID-verified and background-checked so you can trust who you wander with.",
    color: "bg-ocean/10 text-ocean",
  },
  {
    icon: Users,
    title: "Solo-First Matching",
    desc: "Our algorithm connects you with travellers who share your pace, interests, and vibe.",
    color: "bg-sunset/10 text-sunset",
  },
  {
    icon: Compass,
    title: "Local Expert Guides",
    desc: "Access a vetted network of local guides who know the hidden beaches and untouched trails.",
    color: "bg-terra/10 text-terra",
  },
  {
    icon: Globe,
    title: "24/7 Safety Support",
    desc: "Round-the-clock emergency support and real-time location sharing with trusted contacts.",
    color: "bg-ocean/10 text-ocean",
  },
];

export const testimonials = [
  {
    name: "Mia Reyes",
    origin: "Manila → Siargao",
    quote:
      "I was terrified to travel alone. Travel Kin matched me with 3 people who became my closest friends. That wave I caught? Life-changing.",
    avatar:
      "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=200",
    rating: 5,
  },
  {
    name: "Jake Thornton",
    origin: "London → El Nido",
    quote:
      "The local guide recommendation was gold. Hidden lagoons, zero tourists. This is how solo travel should feel — free, safe, and epic.",
    avatar:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200",
    rating: 5,
  },
  {
    name: "Sofia Ruiz",
    origin: "Barcelona → Boracay",
    quote:
      "The safety features gave my parents peace of mind and gave me freedom. Best of both worlds for a 23-year-old exploring solo.",
    avatar:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=200",
    rating: 5,
  },
];

export const stats = [
  { 
    value: "47K+", 
    label: "Solo Travellers",
    description: "Verified solo explorers adventuring safely across Southeast Asia."
  },
  { 
    value: "87", 
    label: "Destinations",
    description: "Curated islands, cities, and jungle escapes across the Philippines and beyond."
  },
  { 
    value: "24/7", 
    label: "Emergency Support",
    description: "Real-time monitoring and local rapid response in 12 SE Asian countries."
  },
  { 
    value: "180+", 
    label: "Local Guides",
    description: "Vetted, community-trusted guides who know every hidden trail and reef."
  },
];

export const tickerItems = [
  "El Nido · Palawan",
  "Siargao · Surf Capital",
  "Boracay · White Beach",
  "Cebu · Canyoneering",
  "Coron · Wreck Diving",
  "Camiguin · Island Life",
  "Bohol · Tarsiers & Rice",
  "Batanes · Edge of the World",
];
